version: '3.7'

services:
    php80:
        tty: true
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                APP_USER_ID: 1000
                APP_GROUP_ID: 1000
                COMPOSER_VERSION: 2.0.12
        volumes:
            - .:/var/www/html
        ports:
            - "8080:8000"
